<a href="https://colab.research.google.com/github/ukeshbhaal/Numpy_and_Pandas_Assignment/blob/main/Numpy_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Aim: Revisiting the numpy
Details: One feature of NumPy that is powerful but tricky is the ability to perform
broadcasting, which really just refers to repeatedly performing an operation over one or more
dimensions.
Tasks:
1. The most basic kind of broadcast is with a scalar, in which you can perform a binary
operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that
operation with the scalar for every element of the array. To try this out, create a vector
1, 2, . . . , 10 by adding 1 to the result of the arange function.
2. Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using
the vector you just created, and adding it to a reshaped version of itself.
3. A very common use of broadcasting is to standardize data, i.e., to make it have zero
mean and unit variance.
a. First, create a fake “data set” with 50 examples, each with five dimensions.
b. import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
c. Don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number
generation library, then generates a 50 × 5 matrix of standard normal random
variates and exponentiates them. The effect of this is to have a pretend data
set of 50 independent and identically-distributed vectors from a log-normal
distribution.

4. Now, compute the mean and standard deviation of each column. This should result in
two vectors of length 5. You’ll need to think a little bit about how to use the axis
argument to mean and std. Store these vectors into variables and print both of them.
5. Now standardize the data matrix by 1) subtracting the mean off of each column, and
2) dividing each column by its standard deviation. Do this via broadcasting, and store
the result in a matrix called normalized. To verify that you successfully did it, compute
the mean and standard deviation of the columns of normalized and print them out.

Part-2

Aim: Performing the Hypothesis testing using the Chi-squared test
The table below is a survey response to 4 categorical variables: people in categories from
18–29, 30–44, 45–64 and >65 years, and their movie genre inclination, which is
“Action/Adventure”, “Romance” and “Biography”. Is there any evidence of a relationship
between the age group and their movie genre inclination, at 5% significance level?

Action/Adventure Romance Biography Total
18-29 141 68 4 213
30-44 179 159 7 345
45-64 220 216 4 440
65&older 86 101 4 191
Total 626 544 19 1189

In [ ]:
import numpy as np
#vector=(,2,3,4,5,6,7,8,9,10)
x=np.arange(1,11)
#print(x)
x1=x+1
print(x1)

[ 2  3  4  5  6  7  8  9 10 11]


In [ ]:
m, n = 10,10
A = np.empty(shape=(m, n), dtype=int)
"""for i in range(m):
    for j in range(n):
        A[i, j] = i+j"""
i, j = np.ogrid[:m, :n]
#print(i,j)
A = i+j
print(A)
"""A = np.add.outer(range(m), range(n))
A"""

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


'A = np.add.outer(range(m), range(n))\nA'

In [ ]:
a = np.zeros((2, 512*512), dtype=np.float32)  
a[1, :] = 1.0  
a[0, :] = 0.1  
print(a)
"""b=np.std(a)  
b """ 

[[0.1 0.1 0.1 ... 0.1 0.1 0.1]
 [1.  1.  1.  ... 1.  1.  1. ]]


'b=np.std(a)  \nb '

In [ ]:
import numpy.random as npr
data = np.exp ( npr.randn(50, 5) )
b=np.std(data,axis=1)
print(b)
c=np.mean(data,axis=1)
print("mean = ",c)


[1.30195138 3.30753626 1.62693569 0.97604152 1.57919709]
mean =  [1.37955338 2.57843818 1.61582634 1.18211856 1.56768657]


In [ ]:
"""Action/Adventure Romance Biography Total
18-29 141 68 4 213
30-44 179 159 7 345
45-64 220 216 4 440
65&older 86 101 4 191
Total 626 544 19 1189"""

In [ ]:
import pandas as pd
data2={'Age':["18-29","30-44","45-64","65&older","Total"],'Action/Adventure':[141,179,220,86,626],'Romance':[68,159,216,101,544],
       'Biography':[4,7,4,4,19],
       'Total':[213,345,440,191,1189]}
df= pd.DataFrame(data2)
df

Age  Action/Adventure  Romance  Biography  Total
0     18-29               141       68          4    213
1     30-44               179      159          7    345
2     45-64               220      216          4    440
3  65&older                86      101          4    191
4     Total               626      544         19   1189

In [ ]:
from scipy.stats import chi2_contingency
  
# defining the table
Data = [[141, 68, 4], [179, 159, 7], [220,216,4], [86,101,4]]
Calculated_ChiSq, p,  Degrees_of_Freedom, Expected_Values = chi2_contingency(Data)
  
# interpret p-value
Alpha = 0.05
print("p value is " + str(p))
if p >= Alpha:
    print('Independent (H0 Holds True / We accept the Null Hypothesis)') #No Co-relation
else:
    print('Dependent (We Reject the H0)') #Co-relation exists

p value is 0.00044690833914947634
Dependent (We Reject the H0)
